"""empty message

Revision ID: 15355e01469b
Revises: 0142386ff66f
Create Date: 2025-12-12 09:32:59.168150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15355e01469b'
down_revision = '0142386ff66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=150), nullable=False),
    sa.Column('isbn', sa.String(length=17), nullable=False),
    sa.Column('ano_pub', sa.Integer(), nullable=False),
    sa.Column('editora', sa.String(length=150), nullable=False),
    sa.Column('paginas', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=100), nullable=False),
    sa.Column('formato', sa.String(length=50), nullable=False),
    sa.Column('idioma', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('capa_livro', sa.String(length=255), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
