"""criação da tabela de empréstimos

Revision ID: 22f77bab55b1
Revises: 8d479f5362a8
Create Date: 2025-12-30 15:32:53.222253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f77bab55b1'
down_revision = '8d479f5362a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leitor_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('data_saida', sa.DateTime(), nullable=False),
    sa.Column('data_prevista', sa.DateTime(), nullable=False),
    sa.Column('data_retorno', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('multa_aplicada', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['leitor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['livro_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    # ### end Alembic commands ###
