"""criação da tabela de leitores

Revision ID: 8d479f5362a8
Revises: c401f0ccbab7
Create Date: 2025-12-15 19:38:49.376437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d479f5362a8'
down_revision = 'c401f0ccbab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=180), nullable=False),
    sa.Column('cidade', sa.String(length=180), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('numero_endereco', sa.String(length=15), nullable=False),
    sa.Column('numero_matricula', sa.Integer(), nullable=False),
    sa.Column('limite_emprestimo', sa.Integer(), nullable=True),
    sa.Column('emprestimos_ativos', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('ultimo_emprestimo', sa.DateTime(), nullable=True),
    sa.Column('responsavel', sa.String(length=255), nullable=True),
    sa.Column('telefone_responsavel', sa.String(length=15), nullable=True),
    sa.Column('obs_interna', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reader', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reader_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_reader_numero_matricula'), ['numero_matricula'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reader', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reader_numero_matricula'))
        batch_op.drop_index(batch_op.f('ix_reader_cpf'))

    op.drop_table('reader')
    # ### end Alembic commands ###
