"""setup inicial

Revision ID: eabb28dc8bf0
Revises: 
Create Date: 2025-12-31 18:23:49.766481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eabb28dc8bf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('autor', sa.String(length=150), nullable=False),
    sa.Column('isbn', sa.String(length=17), nullable=False),
    sa.Column('ano_pub', sa.Integer(), nullable=False),
    sa.Column('editora', sa.String(length=150), nullable=False),
    sa.Column('paginas', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=100), nullable=False),
    sa.Column('formato', sa.String(length=50), nullable=False),
    sa.Column('idioma', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(length=150), nullable=False),
    sa.Column('capa_livro', sa.String(length=255), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books'))
    )
    op.create_table('reader',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('logradouro', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=180), nullable=False),
    sa.Column('cidade', sa.String(length=180), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('numero_endereco', sa.String(length=15), nullable=False),
    sa.Column('numero_matricula', sa.Integer(), nullable=False),
    sa.Column('limite_emprestimo', sa.Integer(), nullable=True),
    sa.Column('emprestimos_ativos', sa.Integer(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('ultimo_emprestimo', sa.DateTime(), nullable=True),
    sa.Column('responsavel', sa.String(length=255), nullable=True),
    sa.Column('telefone_responsavel', sa.String(length=15), nullable=True),
    sa.Column('obs_interna', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reader'))
    )
    with op.batch_alter_table('reader', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reader_cpf'), ['cpf'], unique=True)
        batch_op.create_index(batch_op.f('ix_reader_numero_matricula'), ['numero_matricula'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('usuario', name=op.f('uq_users_usuario'))
    )
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leitor_id', sa.Integer(), nullable=False),
    sa.Column('livro_id', sa.Integer(), nullable=False),
    sa.Column('data_saida', sa.DateTime(), nullable=False),
    sa.Column('data_prevista', sa.DateTime(), nullable=False),
    sa.Column('data_retorno', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('multa_aplicada', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['leitor_id'], ['reader.id'], name=op.f('fk_loans_leitor_id_reader')),
    sa.ForeignKeyConstraint(['livro_id'], ['books.id'], name=op.f('fk_loans_livro_id_books')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loans'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    op.drop_table('users')
    with op.batch_alter_table('reader', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reader_numero_matricula'))
        batch_op.drop_index(batch_op.f('ix_reader_cpf'))

    op.drop_table('reader')
    op.drop_table('books')
    # ### end Alembic commands ###
